vich_uploader:
    db_driver: orm

    mappings:
        product_images:
            uri_prefix:         /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            delete_on_update: true
            namer:
                service: Vich\UploaderBundle\Naming\SmartUniqueNamer